export const CATEGORIES = [
  {
    id: '1',
    name: 'Pain Relief',
    slug: 'pain-relief',
    description: 'Medicines for pain and inflammation',
    image: '/images/categories/pain-relief.jpg',
    icon: '💊',
  },
  {
    id: '2',
    name: 'Vitamins & Supplements',
    slug: 'vitamins',
    description: 'Essential vitamins and dietary supplements',
    image: '/images/categories/vitamins.jpg',
    icon: '🔸',
  },
  {
    id: '3',
    name: 'First Aid',
    slug: 'first-aid',
    description: 'Bandages, antiseptics, and emergency care',
    image: '/images/categories/first-aid.jpg',
    icon: '🩹',
  },
  {
    id: '4',
    name: 'Personal Care',
    slug: 'personal-care',
    description: 'Hygiene and personal care products',
    image: '/images/categories/personal-care.jpg',
    icon: '🧴',
  },
  {
    id: '5',
    name: 'Baby Care',
    slug: 'baby-care',
    description: 'Products for infants and toddlers',
    image: '/images/categories/baby-care.jpg',
    icon: '👶',
  },
  {
    id: '6',
    name: 'Health Devices',
    slug: 'health-devices',
    description: 'Thermometers, BP monitors, and more',
    image: '/images/categories/health-devices.jpg',
    icon: '🩺',
  },
]
