import { Product } from '../types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Panadol Extra 500mg',
    slug: 'panadol-extra-500mg',
    description: 'Fast relief from headaches, fever, and body pain. Contains paracetamol with added caffeine for enhanced effectiveness.',
    price: 149,
    originalPrice: 199,
    discount: 25,
    category: 'Pain Relief',
    categorySlug: 'pain-relief',
    brand: 'GSK',
    image: '/images/products/panadol.jpg',
    inStock: true,
    stock: 50,
    rating: 4.5,
    reviewCount: 128,
    prescription: false,
    tags: ['headache', 'fever', 'pain'],
    features: [
      'Fast acting formula',
      'Suitable for adults',
      '24 tablets per pack',
    ],
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Centrum Multivitamin',
    slug: 'centrum-multivitamin',
    description: 'Complete daily multivitamin with 24 essential nutrients including Vitamin D, B12, and Iron.',
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    category: 'Vitamins & Supplements',
    categorySlug: 'vitamins',
    brand: 'Pfizer',
    image: '/images/products/centrum.jpg',
    inStock: true,
    stock: 30,
    rating: 4.7,
    reviewCount: 89,
    prescription: false,
    tags: ['vitamins', 'health', 'immunity'],
    features: [
      '30 tablets',
      'Boosts immunity',
      'Supports energy',
    ],
    createdAt: '2026-01-10T00:00:00Z',
  },
  {
    id: '3',
    name: 'First Aid Kit Complete',
    slug: 'first-aid-kit-complete',
    description: 'Comprehensive first aid kit with bandages, antiseptic wipes, gauze, scissors, and emergency supplies.',
    price: 899,
    category: 'First Aid',
    categorySlug: 'first-aid',
    image: '/images/products/first-aid.jpg',
    inStock: true,
    stock: 15,
    rating: 4.8,
    reviewCount: 45,
    prescription: false,
    tags: ['emergency', 'safety', 'home'],
    features: [
      '100+ pieces',
      'Portable case',
      'Home & travel use',
    ],
    createdAt: '2026-01-20T00:00:00Z',
  },
]
